baseURL = '/'
languageCode = 'en-us'
title = 'Michael Melei'
theme = 'gokarna'
# theme = 'terminal'

[params]
# contentTypeName = "posts"
# showMenuItems = 3
# Change them to be full width
# fullWidthTheme = true
centerTheme = true

# gokarna theme settings
description="Software Engineer"
socialIcons = [
    {name = "linkedin", url="https://www.linkedin.com/in/michael-melei/"},
    {name = "github", url="https://github.com/mikemel21"},
    {name = "email", url="mailto:michael@meleitech.net"}
]
avatarURL = "/images/avatar.png"

# menu settings
[menu]
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<span data-feather='home'></span>"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
pre = "<span data-feather='info'></span>"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "projects"
name = "Projects"
pre = "<span data-feather='code'></span>"
url = "/projects/"
weight = 3

[[menu.main]]
identifier = "contact"
name = "Contact"
pre = "<span data-feather='mail'></span>"
url = "/contact/"
weight = 4
